from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('', views.home, name="home"),
    path('devloper/', views.devloper, name='devloper'),
    path ('about', views.about, name= "about"),
    path ('Contact', views.Contact, name= "Contact"),
    path ('Service', views.Service, name= "Service"),
    path('member_dashboard',views.member_dashboard,name='member_dashboard'),
    path('deposit_savings',views.deposit_savings, name='deposit_savings'),
    path('apply_loan',views.apply_loan, name='apply_loan'),
    path('purchase_shares',views.purchase_shares, name='purchase_shares'),
    path ('Setting_loan',views.Setting_loan,name='Setting_loan'),
    path('admin_dashboard',views.admin_dashboard,name='admin_dashboard'),
    path ('LoanP',views.LoanP,name='LoanP'),
    path ('pay_loan',views.pay_loan, name='pay_loan'),
    path ('staff_dashboard',views.staff_dashboard, name='staff_dashboard'),
    # path('initiate_stk_push_shares',views.initiate_stk_push_shares, name='initiate_stk_push_shares'),
    path('treasury/buy-shares/<int:member_id>/', views.treasurer_purchase_shares, name='treasurer_buy_shares'),
    path('treasry/deposit-savings/<int:member_id>/', views.treasurer_deposit_savings, name='treasurer_deposit_savings'),

    path ('treasurer_pay_Xloan/<int:loan_id>/', views.treasurer_pay_Xloan ,name='treasurer_pay_Xloan'),
     path ('treasurer_pay_loan/<int:loan_id>/', views.treasurer_pay_loan ,name='treasurer_pay_loan'),
    path ('approve_loan/<int:loan_id>', views.approve_loan, name='approve_loan'),
     path ('download_receipt/<int:saving_id>', views.download_receipt, name='download_receipt'),
   # path ('manage_loan_requests', views.manage_loan_requests, name='manage_loan_requests'),
    path ('record_transaction', views.record_transaction, name='record_transaction'),
    path ('initiate_stk_push', views.initiate_stk_push, name='initiate_stk_push'),
    path ('treasurer_dashboard',views.treasurer_dashboard,name='treasurer_dashboard'),
    path('monthly_repayment_report',views.monthly_repayment_report, name='monthly_repayment_report'),
    path ('all_savings', views.all_savings, name='all_savings'),
    path('my_savings', views.my_savings, name='my_savings'),
    path('my_loans', views.my_loans, name='my_loans'),
    path('member_individual_report', views.member_individual_report, name='member_individual_report'),
    path('my_shares', views.my_shares, name='my_shares'),
    path('loans/pending/', views.pending_loans_view, name='pending_loans'),
    path('loans/approved/', views.approved_loans_view, name='approved_loans'),
    path('loans/rejected/', views.rejected_loans_view, name='rejected_loans'),
    path('loans/Completed/', views.Completed_loans, name='Completed_loans'),
     path('loans/active_loan/', views.active_loan, name='active_loan'),
    path('reject_loan/<int:loan_id>', views.reject_loan, name='reject_loan'),
    path('disburse_loan/<int:loan_id>', views.disburse_loan, name='disburse_loan'),
    path('calculate_loan_risk', views.calculate_loan_risk, name='calculate_loan_risk'),
    path('calculate_penalty',views.calculate_penalty, name='calculate_penalty'),
    path ('Members', views.Members, name='Members'),
     path('disburse_loan_xmass/<int:loan_id>', views.disburse_loan_xmass, name='disburse_loan_xmass'),
     path('Xm_approved', views.Xm_approved,name='Xm_approved'),
     path ('sacco_reportings', views.sacco_reportings, name='sacco_reportings'),
     path('treasurer_edit_loan_amount/<int:loan_id>/', views.treasurer_edit_loan_amount, name='treasurer_edit_loan_amount'),
    path('tran/', views.tran, name='tran'),
    # urls.py
path('respond_guarantor/<int:guarantor_id>/<str:action>/', views.respond_guarantor, name='respond_guarantor'),
path('loan_detail/<int:loan_id>/', views.loan_detail, name='loan_detail'),
path('mpesa_callback/', views.mpesa_callback, name='mpesa_callback'),
path('record_transaction/', views.record_transaction, name='record_transaction'),
path('Human_Resource',views.Human_Resource,name='Human_Resource'),
path('apply-xmas-loan/', views.apply_xmas_loan, name='apply_xmas_loan'),
path('approve_xmas_loan/<int:loan_id>/', views.approve_xmas_loan, name='approve_xmas_loan'),
path('reject_xmas_loan/<int:loan_id>/', views.reject_xmas_loan, name='reject_xmas_loan'),
path('pay-xmas/', views.pay_xmas_loan, name='pay_xmas_loan'),
path('active_xmas_loan',views.active_xmas_loan,name='active_xmas_loan'),
path('monthly_sacco_report', views.monthly_sacco_report, name='monthly_sacco_report'),
path('financial_ledger_view', views.financial_ledger_view, name='financial_ledger_view'),
path('treasurer', views.treasurer, name='treasurer'),
path ('export_sacco_report_csv',views.export_sacco_report_csv,name='export_sacco_report_csv'),

path('sacco_financial_ledger_view', views.sacco_financial_ledger_view, name='sacco_financial_ledger_view'),
path('apply_xmas_refund/', views.apply_xmas_refund, name='apply_xmas_refund'),
path('approve_xmas_refund/<int:refund_id>/', views.approve_xmas_refund, name='approve_xmas_refund'),
path('manage_refunds_list/', views.manage_refunds_list, name='manage_refunds_list'),
path('disburse_xmas_refund/<int:refund_id>/', views.disburse_xmas_refund, name='disburse_xmas_refund'),
path('reject_xmas_refund/<int:refund_id>/', views.reject_xmas_refund, name='reject_xmas_refund'),
path('apply_share_refund/', views.apply_share_refund, name='apply_share_refund'),
path ('capital_share_refund_queue', views.capital_share_refund_queue, name='capital_share_refund_queue'),
path('balance_sheet_view', views.balance_sheet_view, name='balance_sheet_view'),
path ('cancel_share_refund/<int:refund_id>/', views.cancel_share_refund, name='cancel_share_refund'),
path('approve_share_refund/<int:refund_id>/', views.approve_share_refund, name='approve_share_refund'),
path('reject_share_refund/<int:refund_id>/', views.reject_share_refund, name='reject_share_refund'),
path('disburse_share_refund/<int:refund_id>/', views.disburse_share_refund, name='disburse_share_refund'),
 path('my_statement/', views.my_statement, name='my_statement'),
 path('add_expense_view/', views.add_expense_view, name='add_expense_view'),
 path('sacco_report/', views.sacco_report, name='sacco_report'),
 path ('Bank_Statement/', views.Bank_Statement, name='Bank_Statement'),
 path ('bank_financial_report', views.bank_financial_report, name='bank_financial_report'), 
 path ('update_share_goal', views.update_share_goal, name='update_share_goal'),
 path ('update_savings_goal', views.update_savings_goal, name='update_savings_goal'),
 path ('update_targets', views.update_targets, name='update_targets'),
     path('performance_analysis/', views.performance_analysis_view, name='performance_analysis'),
     path ('update_targetds', views.update_targetds, name='update_targetds'),
     path('api/note-details/<str:note_id>/', views.get_note_details, name='note_details'),
     path('member_loan_details_view/<int:profile_id>/', views.member_loan_details_view, name='member_loan_details_view'),
     path ('migrate_single_member_loan/<int:member_id>/', views.migrate_single_member_loan, name='migrate_single_member_loan'),
     path ('migrate_xmas_loan/<int:member_id>/', views.migrate_xmas_loan, name='migrate_xmas_loan'),
  path('bereavement/settings/', views.bereavement_settings, name='bereavement_settings'),
    
    # Admin view - see all member bereavement contribution settings
    # urls.py
path('pay-bereavement-mpesa/', views.pay_bereavement_mpesa, name='pay_bereavement_mpesa'),
path('pay-bereavement-mpesa/<int:announcement_id>/', views.pay_bereavement_mpesa, name='pay_bereavement_mpesa_announcement'),
path('bereavement/treasurer-pay/', views.treasurer_bereavement_pay, name='treasurer_bereavement_pay'),
    path('bereavement/admin/', views.bereavement_admin, name='bereavement_admin'),
path ('bereavement/admin/create/', views.bereavement_admin_create, name='bereavement_admin_create'),
path('treasure/pay/retirement/', views.treasurer_retirement_pay, name='treasurer_retirement_pay'),
    path('bereavement_admin_delete/<int:announcement_id>/', views.bereavement_admin_delete, name='bereavement_admin_delete'),
    path('bereavement_clear_announcement/<int:setting_id>/', views.bereavement_clear_announcement, name='bereavement_clear_announcement'),
path('retirement/collection/report/', views.retirement_collection_report, name='retirement_collection_report'),
path('bereavement-collection-report/', views.bereavement_collection_report, name='bereavement_collection_report'),
path('retirement/create/admin/', views.retirement_admin_create, name='retirement_admin_create'),
path('retirement_admin_delete/<int:announcement_id>/', views.retirement_admin_delete, name='retirement_admin_delete'),
  path('pay-retirement-mpesa/', views.pay_retirement_mpesa, name='pay_retirement_mpesa'),  # <-- ADD THIS LINE
    path('pay-retirement-mpesa/<int:announcement_id>/', views.pay_retirement_mpesa, name='pay_retirement_mpesa_announcement'),
    ]